#!/bin/bash

# Check for elevated privileges
if [ "$EUID" -ne 0 ]; then
    echo "This script requires elevation. Please run as root."
    exit
fi

echo -ne "
------------------------------
MOUNT NETWORK SHARE USING CIFS
------------------------------

"
# Get the username
while true
do
  read -r -p "Username: " username
  if [ -z "$username" ]; then
    echo  "Invalid input..."
  else
    break
  fi
done

# Get the UID
while true
do
  read -r -p "UID (default 1000): " uid
  if [ -z "$uid" ]; then
    echo  "Invalid input..."
  else
    break
  fi
done

# Get the GID
while true
do
  read -r -p "GID (default 1000): " gid
  if [ -z "$gid" ]; then
    echo  "Invalid input..."
  else
    break
  fi
done

# Get the share path
while true
do
  read -r -p "Share path: " share_path
  if [ -z "$share_path" ]; then
    echo  "Invalid input..."
  else
    break
  fi
done

# Get the mount path
while true
do
read -r -p "Mount path: " mount_path
  if [ -z "$mount_path" ]; then
    echo  "Invalid input..."
  else
    break
  fi
done

# Mount the network share using cifs
mount -t cifs -o username="$username",domain=CARS_NT_DOMAIN,uid="$uid",gid="$gid",dir_mode=0755 "$share_path" "$mount_path"